### ISSUE TITLE
Error: Command failed: which java

### ISSUE THREAD

**Issue by toolgood** [mcchatman8009/antlr4-tool#21]
> antlr@1.0.0 generate-parser D:\test\antlr
> antlr4-tool -o parser Expr.g4

Compiling Expr.g4...
'which' is not recognized as an internal or external command,
operable program or batch file.
child_process.js:651
    throw err;
    ^

Error: Command failed: which java
'which' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:611:11)
    at Object.execSync (child_process.js:648:13)
    at D:\test\antlr\node_modules\antlr4-tool\dist\antlr-core\antlr-compiler.js:98:19
    at chdir (D:\test\antlr\node_modules\chdir\index.js:6:13)
    at AntlrCompiler.compileJavaScript (D:\test\antlr\node_modules\antlr4-tool\dist\antlr-core\antlr-compiler.js:97:9)
    at AntlrCompiler.compileTypeScript (D:\test\antlr\node_modules\antlr4-tool\dist\antlr-core\antlr-compiler.js:62:38)
    at D:\test\antlr\node_modules\antlr4-tool\dist\antlr-core\index.js:40:78
    at D:\test\antlr\node_modules\antlr4-tool\dist\antlr-core\index.js:17:23
    at arrayEach (D:\test\antlr\node_modules\lodash\lodash.js:516:11)
    at Function.forEach (D:\test\antlr\node_modules\lodash\lodash.js:9344:14)

**Comment by mcchatman8009** [comment]
@toolgood Ok Thanks for reporting, will fix as soon as I'm able. 

Thanks,

**Comment by LatteAno** [comment]
FYI: I changed `.../node_modules/antlr4-tool/dist/antlr-core/antlr-compiler.js` line #98 from:
```
	child.execSync('which java');
```
to:
```
	child.execSync('where java');
```
And it worked for me. It should be noted that I work in Win10 (`where` is Window's equivalent to Linux's `which` AFAIK).

**Comment by mcchatman8009** [comment]
Okay thanks for the help, I'm going to add that command and test that out.

Thanks @LatteAno

**Comment by nelsonlaquet** [comment]
I really didn't want to modify the package directly, nor did I want to install something like cygwin just for this one tool. Powershell functions and alias didn't work. I resolved it by creating a `which.bat` file in my PATH with the contents outlined in this SU post: https://superuser.com/a/412981/2444

```bat
@echo off
setlocal enabledelayedexpansion

set ext= ;%PATHEXT%
:extloop1
for /f "delims=; tokens=1,*" %%A in ("!ext!") do (
  if exist %1%%A (
    echo .\%1%%A
    goto finish
  )
  set ext=%%B
)
if "!ext!" neq "" goto extloop1

set ext= ;%PATHEXT%
:extloop2
for /f "delims=; tokens=1,*" %%A in ("!ext!") do (
  for %%C in (%1%%A) do (
    if exist %%~$PATH:C (
      echo %%~$PATH:C
      goto finish
    )
  )
  set ext=%%B
)
if "!ext!" neq "" goto extloop2

:finish
endlocal
```
