### ISSUE TITLE
Typescript signatures not generated for alternative labels or rule element labels

### ISSUE THREAD

**Issue by jonfreedman** [mcchatman8009/antlr4-tool#7]
I'm not sure if you're using the ANTLR4 JavaScript target to generate the `.js` files but it appears [rule element labels](https://github.com/antlr/antlr4/blob/master/doc/parser-rules.md#rule-element-labels) are missing from the `.js` source.  In addition to that the `.d.ts` files do not contain definitions for anything defined using an [alternative label](https://github.com/antlr/antlr4/blob/master/doc/parser-rules.md#alternative-labels).  The corresponding enter/exit methods are also missing from the `Listener.d.ts` and the context classes from `Parser.d.ts`.

**Comment by mcchatman8009** [comment]
@jonfreedman I'll be sure to address this. Alternative labels can be very useful. Especially, for improving existing grammars.

**Comment by jonfreedman** [comment]
I started to have a look at this, it seems to me that in `parser-utils.ts` you need to keep the Parser constructor function and pull properties off that in order to get the full list of `contextRuleNames`.  As you're familiar with the code I'm not sure if you could get this working easily, or if it's actually fairly involved.

**Comment by alwonder** [comment]
@jonfreedman 
Hey there!

Recently I created the [pull request](https://github.com/mcchatman8009/antlr4-tool/pull/11) for adding alternative labels in parser's 'module.exports' and .d.ts file. You could try it out.

**Comment by mcchatman8009** [comment]
@alwonder you pull request looks great! I have another approach to dealing with this in my next minor version update that allows for a bit more of an elegant solution. Which allows for the removal of the hard dependency of the `parser-util` module, and some of it's runtime nature. Hopefully, I can get that in you guys hand soon for further review.

Thanks again @jonfreedman & @alwonder. I'm closing this issue
